# Project Information
site_name: Responsible AI Playbook
site_description: A playbook for Responsible AI in the Singapore Public Service
site_author: GovTech AI Practice
site_dir: ../docs
docs_dir: docs

# Theme Configuration
theme:
  name: material
  language: en
  palette:
    primary: indigo
    accent: pink
  features:
    - navigation.tabs
    - toc.integrate

# Markdown Extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
    
# Navigation
nav:
  - Home: index.md
  - Testing: testing.md
  - Guardrails:
    - Overview: guardrails.md
    - Getting Started: guardrails/getting_started.md
    - Best Practices When Integrating Guardrails: guardrails/best_practices.md
    - Building Your Own Guardrails: guardrails/byog.md
  - Fairness: fairness.md

# Plugins
plugins:
  - search
  - section-index
  - exclude:
      glob:
        - "*.tmp"
        - "*.bak"