import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: 'category',
      label: 'Start Here',
      collapsed: false,
      items: [
        'start-here/choose-your-path',
        'start-here/minimum-bar-before-launch',
        'start-here/lifecycle',
        'start-here/application-types',
        'start-here/glossary',
      ],
    },
    {
      type: 'category',
      label: 'Understanding Risks',
      link: {type: 'doc', id: 'understanding-risks/index'},
      collapsed: true,
      items: [
        'understanding-risks/intended-prohibited-use',
        'understanding-risks/application-risk-profile',
        'understanding-risks/risk-categories',
        'understanding-risks/agentic-risk-model',
        'understanding-risks/agentic-risk-categories',
        'understanding-risks/launch-criteria-risk-register',
      ],
    },
    {
      type: 'category',
      label: 'Evaluating AI Systems',
      link: {type: 'doc', id: 'evaluating-ai-systems/index'},
      collapsed: true,
      items: [
        'evaluating-ai-systems/functional',
        'evaluating-ai-systems/safety',
        'evaluating-ai-systems/robustness',
        'evaluating-ai-systems/fairness',
        'evaluating-ai-systems/privacy',
        'evaluating-ai-systems/agentic-evals',
        'evaluating-ai-systems/methods',
      ],
    },
    {
      type: 'category',
      label: 'Mitigations & Controls',
      link: {type: 'doc', id: 'mitigations-controls/index'},
      collapsed: true,
      items: [
        'mitigations-controls/guardrail-architecture',
        'mitigations-controls/pii-guardrails',
        'mitigations-controls/content-safety',
        'mitigations-controls/prompt-injection-jailbreak',
        'mitigations-controls/hallucination-grounding',
        'mitigations-controls/off-topic-scope',
        'mitigations-controls/system-prompt-leakage',
        'mitigations-controls/threshold-tuning',
        'mitigations-controls/measuring-impact',
        'mitigations-controls/building-your-own-guardrail',
        'mitigations-controls/production-integration',
        'mitigations-controls/agentic-safety-controls',
        'mitigations-controls/monitoring-incident-response',
      ],
    },
    {
      type: 'category',
      label: 'Tools & Benchmarks',
      link: {type: 'doc', id: 'tools/index'},
      collapsed: true,
      items: [
        'tools/litmus',
        'tools/sentinel',
        'tools/lionguard',
        'tools/rabakbench',
        'tools/minorbench',
        'tools/responsible-ai-benchmark',
        'tools/pii-test-set-template',
        'tools/eval-dataset-template',
        'tools/human-annotation-template',
        'tools/llm-as-judge-template',
        'tools/guardrail-tuning-template',
        'tools/agentic-risk-assessment-template',
      ],
    },
    {
      type: 'category',
      label: 'Resources',
      link: {type: 'doc', id: 'deep-dives/index'},
      collapsed: true,
      items: [
        'deep-dives/safety',
        'deep-dives/fairness',
        'deep-dives/robustness',
        'deep-dives/privacy',
        'deep-dives/interpretability',
        'deep-dives/llm-evaluation',
        'deep-dives/guardrails',
        'deep-dives/agentic-safety',
        'resources',
        'our-work/index',
        'getting-started/contributing',
        'contributing/page-standards',
      ],
    },
  ],
};

export default sidebars;
